---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Delete VM From Storage Domain
    name: delete_vm
    inherits: 
    description: 
  fields:
  - meth1:
      value: delete_vm
